### ISSUE TITLE
Warning after bulk update

### ISSUE THREAD

**Issue by enzolutions** [backdrop-contrib/pathauto#1] opened 2015-01-20 02:16 UTC
After run a bulk update I get the following warnings related with langcode

```
Warning: Illegal offset type in pathauto_cleanstring() (line 189 of /Users/enzo/www/backdrop/modules/contrib/pathauto/pathauto.inc).
Warning: Illegal offset type in pathauto_cleanstring() (line 235 of /Users/enzo/www/backdrop/modules/contrib/pathauto/pathauto.inc).
Warning: Illegal offset type in pathauto_cleanstring() (line 189 of /Users/enzo/www/backdrop/modules/contrib/pathauto/pathauto.inc).
Warning: Illegal offset type in pathauto_cleanstring() (line 235 of /Users/enzo/www/backdrop/modules/contrib/pathauto/pathauto.inc).
```

Any ideas?

**Comment by klonos** [comment] 2015-01-26 10:16
Please close this one as a duplicate of #6 (I know this issue here is older, but the other one has a pull request)

**Comment by quicksketch** [comment] 2015-02-01 03:13
Fixed in https://github.com/backdrop-contrib/pathauto/issues/6.

**Closed as completed by quicksketch** 2015-02-01 03:13 UTC
